[pytest]
# Register markers
markers = 
    unit: marks tests as unit tests (deselect with '-m "not unit"')
    performance: marks tests as performance tests (deselect with '-m "not performance"')
    integration: marks tests as integration tests (deselect with '-m "not integration"')

addopts =
    -v
    --strict-markers