[pytest]
# testpaths = ["tests"]
# Register markers
markers = 
    unit: marks tests as unit tests (deselect with '-m "not unit"')
    performance: marks tests as performance tests (deselect with '-m "not performance"')
    insertion: marks tests as insertion tests (deselect with '-m "not insertion"')
    merge: marks tests as merge tests (deselect with '-m "not merge"')
    search: marks tests as search tests (deselect with '-m "not search"')
# python_files = ["test_*.py"]
# python_classes = ["Test*"]
# python_functions = ["test_*"]
addopts =
    -v
    --strict-markers
# pythonpath = ["."]